### ISSUE TITLE
Show an example of how to do inter-app communication

### ISSUE THREAD

**Issue by internettrans** [joeldenning/single-spa-examples#10]
See https://github.com/CanopyTax/single-spa-examples/issues/7#issuecomment-260008143

**Comment by daniele-zurico** [comment]
I got lost between the links ... is the inter-app communication have been implemented? Thanks in advance

**Comment by internettrans** [comment]
The inter-app communication is already occurring with the "framework inspector" that is turned on/off and then all apps respect that.

However, it's not documented or even commented in the code. Also, inter-app communication is a big enough topic where maybe there should be a few different examples of how to do it.

**Comment by internettrans** [comment]
Closing for now -- feel free to reopen with further questions or discussion
