### ISSUE TITLE
No CORS file (preventing me from pulling a remote child application)

### ISSUE THREAD

**Issue by TheMcMurder** [joeldenning/single-spa-examples#29]
Surge supports adding a CORS file. I'll submit a pull request to add a [CORS file](https://surge.sh/help/enabling-cross-origin-resource-sharing).

Basically I'd like to ensure my parent application is set up correctly. If I add a CORS file to the deploy on surge then I can pull the deployed file as a child application of my local application to ensure I set it up correctly.

**Comment by internettrans** [comment]
CORS requires paid plan with surge. To do this we'd have to switch off of surge
