### ISSUE TITLE
SystemJS not found while cloning the repo and running for the first time

### ISSUE THREAD

**Issue by avinash195** [joeldenning/single-spa-examples#35]
single-spa is very promising library for our microservices architecture and i have been trying to implement it for a few days.But while cloning this repo and running after npm install it throws errors like SystemJS not found(GET /build/system-polyfills.src.js" Error (404): "Not found"   ,  GET /build/common-deps.js" Error (404): "Not found"   ,   GET /build/system.src.js" Error (404): "Not found" ,    GET /build/shared.src.js" Error (404): "Not found"

**Comment by internettrans** [comment]
Happy to hear you are trying out single-spa! Let us know if you have any questions or run into problems.

When was the last time you pulled? Five days ago I [made a commit](https://github.com/CanopyTax/single-spa-examples/commit/5f51433f780bc7b59ff62bd0c11c1dd1b365bca8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40) that fixed the problem you described in your issue. What was happening is that this project only works with `jspm@0.17.0-beta.32` or lower, there was a major change made in beta.33 that broke single-spa-examples until we make some changes so we can upgrade. I think that what we should do is just make the necessary code changes to upgrade to the latest jspm and systemjs (see https://github.com/CanopyTax/single-spa-examples/issues/36), but until then we need to be on beta.32.

Let me know if git pull doesn't fix anything for you. Also, you might need to delete the node_modules and jspm_packages directories after you pull to make sure that the jspm install works.

**Comment by avinash195** [comment]
It's working now.Thanks
