### ISSUE TITLE
Switch to all webpack and no jspm?

### ISSUE THREAD

**Issue by internettrans** [joeldenning/single-spa-examples#38]
Webpack is much more popular and is sort of the community standard. It might make things easier for people to understand and use if webpack is used in this repo rather than jspm

**Comment by daniele-zurico** [comment]
Any news on that?

**Comment by internettrans** [comment]
Fixed with https://github.com/CanopyTax/single-spa-examples/commit/0dc6e7639b9a4f9502d5324baa3ae5d3f4a85eac
