### ISSUE TITLE
feature request Linting

### ISSUE THREAD

**Issue by area73** [joeldenning/single-spa-examples#49]
Adding lint like JSCS to homogeneizar coding.
Do you think is it a good idea?

**Comment by internettrans** [comment]
Hey @area73! Thanks for creating this issue and for the pr you created earlier today!

The single-spa-examples project demos the capabilities of single-spa, but is not really intended to be like create-react-app or angular-cli which prescribe how to build an application. So whether it's linted or not shouldn't have a huge impact on lots of people using single-spa.

That being said, I'm open to adding a linter that checks for bugs without being very heavy handed about style. I prefer a little stylistic freedom, personally, but if a tool like eslint can find bugs, that's great.

**Comment by internettrans** [comment]
Closing for now -- feel free to reopen or submit a PR
