### ISSUE TITLE
Question: Are all applications required at build time?

### ISSUE THREAD

**Issue by egucciar** [joeldenning/single-spa-examples#50]
Ideally, Single-spa app loader would not need to rely on static build time to get new app. I would like to release a build for application A, while not having to do any build for application B. Does single spa allow for this, or would we need to re-build the entire platform whenever an app is updated?

**Comment by internettrans** [comment]
Great question! The single-spa-examples repo is set up to just have one build (and one webpack config), but having a separate build for each application is totally possible. Check out the newly created [separating applications docs](https://github.com/CanopyTax/single-spa/blob/master/docs/separating-applications.md), which go over your options for this. Specifically the module loading section is hopefully helpful.

I'm closing this issue for now, but feel free to reopen with more questions or discussion.
