### ISSUE TITLE
Cannot GET /build/vanillajs/index.html

### ISSUE THREAD

**Issue by 0x1428571429** [joeldenning/single-spa-examples#53]
Cannot GET /build/vanillajs/index.html

**Comment by internettrans** [comment]
Did you run `yarn build` before `yarn start`? Running the build copies the vanillajs/index.html file into the build directory. If so, maybe the build failed before it got to that part?

To fix it, try running [yarn build-vanilla](https://github.com/CanopyTax/single-spa-examples/blob/master/package.json#L10), which will run just that particular part of the build.

**Comment by 0x1428571429** [comment]
yarn build before yarn start 

Thank you
