### ISSUE TITLE
Would it be useful to have E2E tests with Cypress?

### ISSUE THREAD

**Issue by bahmutov** [joeldenning/single-spa-examples#62]
Love the idea, and the examples. Would it make sense to add end-to-end tests using Cypress.io for this repo?

**Comment by internettrans** [comment]
Apologies for the slow response - I'm not opposed to adding some more tests to this repo. We haven't had many issues with bugs creeping in, so I don't think there has been a pressing need to do so. But would be open to discussing it and reviewing PRs that add tests.
