### ISSUE TITLE
Ember example from single-spa.surge.sh not working

### ISSUE THREAD

**Issue by mihailgaberov** [joeldenning/single-spa-examples#69]
![image](https://user-images.githubusercontent.com/2501904/59830837-bd062f80-9340-11e9-8149-d69922d9c110.png)

**Comment by internettrans** [comment]
I've known about this for a while.

single-spa-examples is due for a redo -- it hasn't been touched in a year or two. PRs accepted to fix the ember app as-is, or we can wait for the redo.

**Comment by JenniferFuBook** [comment]
Can we merge the PR to get a working Ember example?
