### ISSUE TITLE
The example website(single-spa.surge.sh) running error

### ISSUE THREAD

**Issue by xieyihao** [joeldenning/single-spa-examples#71]
**Describe the bug or question**
The Official website's example running error. [https://single-spa.surge.sh/](https://single-spa.surge.sh/).

**To Reproduce**
And I found an error in console.
<pre>
Uncaught ReferenceError: webpackJsonp is not defined
    at main.js:1
</pre>

**Expected behavior**
Run well.

**Screenshots and/or console output**
![image](https://user-images.githubusercontent.com/12508868/59965352-4e42f500-953f-11e9-86a3-1ea9aae47c97.png)

**Additional context**
No more

**Comment by internettrans** [comment]
I do not get this error. Can you provide more information to help replicate the issue? What browser are you on? Can you replicate the error every time?

**Comment by xieyihao** [comment]
It run well now :sweat:

The error was repeated every time，the day before yesterday。It may cause by Network。
My system & browser : Chrome 74.0.3729.169 | macOS 10.14.5 。

thx for your attention.
